version: '3.8'

services:
  myapp:
    image: yii2:latest
    container_name: myapp
    volumes:
      - /var/www/html/web:/var/www/html/web
    ports:
      - "9000:9000"
    restart: unless-stopped
